---
title: "levelTest_ans"
author: "linsq"
date: "2017年3月7日"
output: 
  pdf_document: 
    latex_engine: xelatex
    includes:
          in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##第1题

编写一个函数findNum(y,l)计算在y向量中数字1连续出现l次的位置
时间：5 min

```{r}
y<- c(1,0,0,1,1,1,0,1,1)
findNum <- function(y,x,l){
        Num <- NULL
        for(i in 1:(length(y)-l+1)){
                if(all(y[i:(i+l-1)]==x)){
                        Num <- c(Num,i)
                }
        }
        return(Num)
}
findNum(y,1,2)
```

##第2题

计算每天最低气温和最高气温的差值
时间：7min

```{r}
raw <- read.delim("~/R/weather.txt",check.names = F, na.strings = ".")
library(data.table)
raw <- data.table(raw)
#diff <- raw[,lapply(.SD[,-c(1:2)],function(x){x[1]-x[2]}),by=month]
diff <- raw[,lapply(.SD[,-c("element")],function(x){x[1]-x[2]}),by=.(year,month)]
diff

#以下是新加的转化
diff_temp <- na.omit(melt(diff,measure.vars = colnames(diff)[-1],variable.name = "day",value.name = "diff_temp"))
setorder(diff_temp,year,month,day)
diff_temp
```

##第3题

测试：计算每个航空公司(UniqueCarrier)每个月到达延误时间(ArrDelay)的十分位(quantile)的均值

时间：5 min

原本理解：各个航空公司的延误时间的每个月在10%分位数上的均值。
```{r}
library(hflights)
dat <- data.table(hflights)
dat1<- dat[,.(delay=quantile(na.omit(ArrDelay),0.1)),by=.(Year,Month,UniqueCarrier)]
#dat1<- dat[,.(quantile(na.omit(ArrDelay),seq(0,1,0.1))),by=.(Year,Month,UniqueCarrier)]
dat1[,.(meandelay=mean(delay)),by=UniqueCarrier]
```

各航空公司的每个月的延误时间在每个十分位上的均值。

时间：15 min
```{r}
library(hflights)
library(data.table)
dat <- data.table(hflights)
dat <- na.omit(dat[,.(Year,Month,UniqueCarrier,ArrDelay)])
dat_qua <- dat[,quan:=findInterval(ArrDelay,quantile(ArrDelay,seq(0,1,0.1)),rightmost.closed = TRUE),
            by=.(UniqueCarrier,Year,Month)]
dat_qua <- setorder(dat_qua,UniqueCarrier,Year,Month,quan)
dat_delay<- dat_qua[,.(meandelay=mean(ArrDelay)),by=.(UniqueCarrier,Year,Month,quan)]
head(dat_delay)

dat_qua2 <- dat[,quan:=f1(ArrDelay),by=.(UniqueCarrier,Year,Month)]
dat_qua2 <- setorder(dat_qua2,UniqueCarrier,Year,Month,quan)
dat_delay2<- dat_qua2[,.(meandelay=mean(ArrDelay)),by=.(UniqueCarrier,Year,Month,quan)]
head(dat_delay2)
```

tapply:多个分组


参考答案
```{r}
library(dplyr)
library(hflights)

rs<-na.omit(hflights) %>% 
  select(UniqueCarrier,Year,Month,ArrDelay) %>%
  group_by(UniqueCarrier,Year,Month) %>%
  mutate(quan=findInterval(ArrDelay,quantile(ArrDelay,seq(0,1,0.1)),da)) %>% 
  group_by(UniqueCarrier,Year,Month,quan) %>%
  summarise(avgQuan=mean(ArrDelay,na.rm=T))

head(rs)
```
summaries:添加新列
mutate:对每一行都要计算
不用包再做一遍

```{r}
x <- rnorm(100)

f1 <- function(x){
        inter <- rep(NA,length(x))
        quan <- quantile(x,seq(0,1,0.1))
        inter[which.min(x)] <- 1
        for(i in 1:length(x)){
                for(j in 1:10){
                        if(x[i]>quan[j] & x[i]<=quan[j+1]){
                                inter[i] <- j
                        }#else{j = j+1}
                }
        }
        inter
}
a1 <- f1(x)

a2 <- findInterval(x,quantile(x,seq(0,1,0.1)),rightmost.closed = TRUE)
```

